str1="hello"
str2="chauhan"
str3="hello"
print("hello"=="hello")
print("Hello"=="hello")
print(str1==str2)
print(str2==str3)
print(str1>str2)
print(str2>str3)
print(str1<str2)
print(str2<str3)
print(str1!=str2)
print(str2!=str3)